services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./broker_conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
